title: <p align="center"> Yebei Rong </p># your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yebeirong/">LinkedIn</a> |
  <a href="https://github.com/Yebei-Rong">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Mathematical Finance at Questrom Business School, Boston University.
  <br><br>
  I am actively looking for full-time jobs 2021 related to data analysis.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
